services:
  db:
    image: postgres:15.5-alpine3.19
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
      PYTHONUNBUFFERED: 1
    volumes:
      - ./src:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db

  nginx:
    image: nginx:1.19.2
    container_name: web_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/django.conf:/etc/nginx/conf.d/django.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      web:
        condition: service_started
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  static_volume:
  media_volume:
